export const OVERRIDE_REASONS = {
  CUSTOMER_REQUEST: 'CUSTOMER_REQUEST',
  KITCHEN_ERROR: 'KITCHEN_ERROR',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  STAFF_OVERRIDE: 'STAFF_OVERRIDE',
  DUPLICATE_ORDER: 'DUPLICATE_ORDER',
  SYSTEM_RECOVERY: 'SYSTEM_RECOVERY',
  OTHER: 'OTHER',
}
